vnoremap <C-c> "+y
set number
"set relativenumber
set nocompatible
set ignorecase
syntax on
set wildmode=longest,list
set ttyfast
set wildmode=longest,list
set autoindent
set smartindent
call plug#begin()
Plug 'EdenEast/nightfox.nvim',
Plug 'nvim-tree/nvim-web-devicons'
Plug 'nvim-lua/plenary.nvim'
Plug 'lewis6991/gitsigns.nvim'
Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'MeanderingProgrammer/render-markdown.nvim'
call plug#end()
colorscheme carbonfox
