[colors]
background = 202020
foreground = d0d0d0


selection-background = eecb8b
selection-foreground = 232323

regular0 = 151515
regular1 = ac4142
regular2 = 7e8d50
regular3 = e5b566
regular4 = 6c99ba
regular5 = 9e4e85
regular6 = 7dd5cf
regular7 = d0d0d0

# Bright colors
bright0 = 505050
bright1 = ac4142
bright2 = 7e8d50
bright3 = e5b566
bright4 = 6c99ba
bright5 = 9e4e85
bright6 = 7dd5cf
bright7 = f5f5f5
