# Core Colors
background            #181114
foreground            #eedfe3
selection_foreground  #fdb0d4
selection_background  #521d3b
cursor                #fdb0d4
cursor_text_color     #181114

# Regular Colors
color0  #181114               
color1  #ffb4ab                 
color2  #fdb0d4               
color3  #f2bb9a              
color4  #ffd8e8  
color5  #fdd9e7
color6  #e0bdcb             
color7  #eedfe3            

# Bright Colors
color8  #40373a         
color9  #ffb4ab                  
color10 #fdb0d4                
color11 #f2bb9a               
color12 #ffd8e8   
color13 #fdd9e7 
color14 #e0bdcb              
color15 #eedfe3  
