[main]
include=~/.config/foot/themes/noctalia

#  ┏┓┏┓┏┓┏┳┓
#  ┣ ┃┃┃┃ ┃ 
#  ┻ ┗┛┗┛ ┻ 

#-------------------------#
shell=fish
#term=xterm-256color

#----------------------------#
font=Liberation Mono:size=10

#-----------------------------------------#
pad=15x15 center
#include=~/.config/foot/dank-colors.ini
#include=~/.config/foot/aw.ini
#include=~/.config/foot/footmatugen.ini
#--------------------------------#
[key-bindings]
font-increase=Mod1+Shift+plus
font-decrease=Mod1+Shift+minus

search-start=Mod1+f

#--------------------------------#
[scrollback]
indicator-position=fixed
indicator-format=percentage
[colors-dark]
alpha=0.9
